easy_admin:
   entities:
        Courses:
            class : App\Entity\Courses
            form:
                fields:
                    - { property : name}
                    - { property : description }
                    - { property : content , type : fos_ckeditor, type_options: { config_name: my_config } }
                    - { property : image, type : file}
                    - { property : categories}
        User:
            class:  App\Entity\User
        Categories:
            class: App\Entity\Categories

    design:
        menu:
            # no permission defined, so all users can see this menu item
            - { entity: 'Courses' }

            # only users with the ROLE_SUPER_ADMIN role will see this menu item
            - { entity: 'User', permission: 'ROLE_ADMIN' }
            - { entity: 'Categories', permission: 'ROLE_ADMIN' }

            # when defining multiple roles, the user must have at least one of them
            # or all of them, depending on the configuration of your Symfony application
            # by default: user must have at least one of the roles
            # see https://symfony.com/doc/current/security/access_control.html#access-enforcement
            
